config/routes.rb
Rails.application.routes.draw do
  resources :property_names
  resources :unit_types
  resources :properties
   root  to: "properties#index"

   get "/pages/*page" => "pages#home"
   

   get '/login' => 'sessions#new'
   post '/login' => 'sessions#create'
   get '/logout' => 'sessions#destroy'
   get '/renewal' => 'properties#renewal'

   get '/update' => 'properties#update'
   post '/update' => 'properties#submit'

   get '/raw' => 'properties#raw'
   get '/rawren' => 'properties#rawren'
   get '/mbc' => 'properties#mbc'



  resources :properties
  #   member do
  #     get 'report'
  #   end
  # end

  resources :employees
  resources :companies
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html


end

app/models/property_name.rb
class PropertyName < ApplicationRecord
  has_many :unit_types
  has_many :properties, through: :unit_types
end

app/controllers/property_names_controller.rb
class PropertyNamesController < ApplicationController
  before_action :set_property_name, only: [:show, :edit, :update, :destroy]

  # GET /property_names
  # GET /property_names.json
  def index
    @property_names = PropertyName.all
  end

  # GET /property_names/1
  # GET /property_names/1.json
  def show
  end

  # GET /property_names/new
  def new
    @property_name = PropertyName.new
  end

  # GET /property_names/1/edit
  def edit
  end

  # POST /property_names
  # POST /property_names.json
  def create
    @property_name = PropertyName.new(property_name_params)

    respond_to do |format|
      if @property_name.save
        format.html { redirect_to @property_name, notice: 'Property name was successfully created.' }
        format.json { render :show, status: :created, location: @property_name }
      else
        format.html { render :new }
        format.json { render json: @property_name.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /property_names/1
  # PATCH/PUT /property_names/1.json
  def update
    respond_to do |format|
      if @property_name.update(property_name_params)
        format.html { redirect_to @property_name, notice: 'Property name was successfully updated.' }
        format.json { render :show, status: :ok, location: @property_name }
      else
        format.html { render :edit }
        format.json { render json: @property_name.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /property_names/1
  # DELETE /property_names/1.json
  def destroy
    @property_name.destroy
    respond_to do |format|
      format.html { redirect_to property_names_url, notice: 'Property name was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_property_name
      @property_name = PropertyName.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def property_name_params
      params.require(:property_name).permit(:name,:lease_terms)
    end
end

app/helpers/property_names_helper.rb
module PropertyNamesHelper
end

app/views/property_names/_form.html.erb
<%= form_for(property_name) do |f| %>
  <% if property_name.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(property_name.errors.count, "error") %> prohibited this property_name from being saved:</h2>

      <ul>
      <% property_name.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>


  <div class="field">
    <%= f.label :name %>
    <%= f.text_field :name %>
  </div>

  <div class="field">
    <%= f.label :lease_terms %>
    <%= f.text_field :lease_terms %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/property_names/edit.html.erb
<h1>Editing Property Name</h1>

<%= render 'form', property_name: @property_name %>

<%= link_to 'Show', @property_name %> |
<%= link_to 'Back', property_names_path %>

app/views/property_names/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Property Names</h1>

<table>
  <thead>
    <tr>
      <th>Property Name</th>
      <th>Lease terms</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @property_names.each do |property_name| %>
      <tr>
        <td><%= property_name.name %></td>
        <td><%= property_name.lease_terms %></td>
        <td><%= link_to 'Show', property_name %></td>
        <td><%= link_to 'Edit', edit_property_name_path(property_name) %></td>
        <td><%= link_to 'Destroy', property_name, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Property Name', new_property_name_path %>

app/views/property_names/new.html.erb
<h1>New Property Name</h1>

<%= render 'form', property_name: @property_name %>

<%= link_to 'Back', property_names_path %>

app/views/property_names/show.html.erb
<p id="notice"><%= notice %></p>
<p>
  <strong>Property name:</strong>
  <%= @property_name.name %>
</p>
<p>
  <strong>Lease terms:</strong>
  <%= @property_name.lease_terms %>
</p>

<%= link_to 'Edit', edit_property_name_path(@property_name) %> |
<%= link_to 'Back', property_names_path %>