config/routes.rb
Rails.application.routes.draw do
  resources :property_names
  resources :unit_types
  resources :properties
   root  to: "properties#index"

   get "/pages/*page" => "pages#home"
   

   get '/login' => 'sessions#new'
   post '/login' => 'sessions#create'
   get '/logout' => 'sessions#destroy'
   get '/renewal' => 'properties#renewal'

   get '/update' => 'properties#update'
   post '/update' => 'properties#submit'

   get '/raw' => 'properties#raw'
   get '/rawren' => 'properties#rawren'
   get '/mbc' => 'properties#mbc'



  resources :properties
  #   member do
  #     get 'report'
  #   end
  # end

  resources :employees
  resources :companies
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html


end

app/controllers/unit_types_controller.rb
class UnitTypesController < ApplicationController
  before_action :set_unit_type, only: [:show, :edit, :update, :destroy]

  # GET /unit_types
  # GET /unit_types.json
  def index
    @unit_types = UnitType.all
  end

  # GET /unit_types/1
  # GET /unit_types/1.json
  def show
  end

  # GET /unit_types/new
  def new
    @unit_type = UnitType.new
  end

  # GET /unit_types/1/edit
  def edit
  end

  # POST /unit_types
  # POST /unit_types.json
  def create
    @unit_type = UnitType.new(unit_type_params)

    respond_to do |format|
      if @unit_type.save
        format.html { redirect_to @unit_type, notice: 'Unit type was successfully created.' }
        format.json { render :show, status: :created, location: @unit_type }
      else
        format.html { render :new }
        format.json { render json: @unit_type.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /unit_types/1
  # PATCH/PUT /unit_types/1.json
  def update
    respond_to do |format|
      if @unit_type.update(unit_type_params)
        format.html { redirect_to @unit_type, notice: 'Unit type was successfully updated.' }
        format.json { render :show, status: :ok, location: @unit_type }
      else
        format.html { render :edit }
        format.json { render json: @unit_type.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /unit_types/1
  # DELETE /unit_types/1.json
  def destroy
    @unit_type.destroy
    respond_to do |format|
      format.html { redirect_to unit_types_url, notice: 'Unit type was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_unit_type
      @unit_type = UnitType.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def unit_type_params
      params.require(:unit_type).permit(:type, :bedroom, :amount_off, :percentage_off, :growth_rate, :increase_amount, :market_rate_date, :property_name_id)
    end
end

app/helpers/unit_types_helper.rb
module UnitTypesHelper
end

app/views/unit_types/_form.html.erb
<%= form_for(unit_type) do |f| %>
  <% if unit_type.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(unit_type.errors.count, "error") %> prohibited this unit_type from being saved:</h2>

      <ul>
      <% unit_type.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  

  <div class="field">
    <%= f.label :unit_type %>
    <%= f.text_field :unit_type %>
  </div>


  <div class="field">
    <%= f.label :bedroom %>
    <%= f.text_field :bedroom %>
  </div>

  <div class="field">
    <%= f.label :amount_off %>
    <%= f.number_field :amount_off %>
  </div>

  <div class="field">
    <%= f.label :percentage_off %>
    <%= f.text_field :percentage_off %>
  </div>

  <div class="field">
    <%= f.label :growth_rate %>
    <%= f.text_field :growth_rate %>
  </div>

  <div class="field">
    <%= f.label :increase_amount %>
    <%= f.text_field :increase_amount %>
  </div>

  <div class="field">
    <%= f.label :market_rate_date %>
    <%= f.text_field :market_rate_date %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/unit_types/edit.html.erb
<h1>Editing Unit Type</h1>

<%= render 'form', unit_type: @unit_type %>

<%= link_to 'Show', @unit_type %> |
<%= link_to 'Back', unit_types_path %>

app/views/unit_types/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Unit Types</h1>

<table>
  <thead>
    <tr>
      <th>Prop<th>
      <th>Type</th>
      <th>Bedroom</th>
      <th>Amount off</th>
      <th>Percentage off</th>
      <th>Growth Rate</th>
      <th>Renewal Increase</th>
      <th>Market Rate Date</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @unit_types.each do |unit_type| %>
      <tr>
        <td><%= unit_type.property_name.name%><td>
        <td><%= unit_type.unit_type %></td>
        <td><%= unit_type.bedroom %></td>
        <td><%= unit_type.amount_off %></td>
        <td><%= unit_type.percentage_off %></td>
        <td><%= unit_type.growth_rate %></td>
        <td><%= unit_type.increase_amount %></td>
        <td><%= unit_type.market_rate_date %></td>
        <td><%= link_to 'Show', unit_type %></td>
        <td><%= link_to 'Edit', edit_unit_type_path(unit_type) %></td>
        <td><%= link_to 'Destroy', unit_type, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Unit Type', new_unit_type_path %>

app/views/unit_types/new.html.erb
<h1>New Unit Type</h1>

<%= render 'form', unit_type: @unit_type %>

<%= link_to 'Back', unit_types_path %>

app/views/unit_types/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Unit Type:</strong>
  <%= @unit_type.unit_type %>
</p>


<p>
  <strong>Bedroom:</strong>
  <%= @unit_type.bedroom %>
</p>

<p>
  <strong>Amount off:</strong>
  <%= @unit_type.amount_off %>
</p>

<p>
  <strong>Percentage off:</strong>
  <%= @unit_type.percentage_off %>
</p>

<p>
  <strong>Type:</strong>
  <%= @unit_type.growth_rate %>
</p>

<p>
  <strong>Type:</strong>
  <%= @unit_type.increase_amount%>
</p>

<p>
  <strong>Type:</strong>
  <%= @unit_type.market_rate_date %>
</p>

<%= link_to 'Edit', edit_unit_type_path(@unit_type) %> |
<%= link_to 'Back', unit_types_path %>